name: monorepo
description: Base project for modularity in flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  login:
    path: packages/features/login/login

  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  get_it: ^8.0.3
  injectable: ^2.5.0


dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  melos: ^6.3.2
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.1.0
  injectable_generator: ^2.5.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
