name: base_dependencies
description: A Very Good Project created by Very Good CLI.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0