name: ui
description: A package that contain shared ui in whole project.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  ui_dependencies:
    path: ../shared_dependency/ui_dependencies

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

dev_dependencies:
  bloc_test: 9.1.7
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: 6.0.0

flutter:
  uses-material-design: true
  generate: true
