name: utils
description: A Very Good Project created by Very Good CLI.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  base_dependencies:
    path: ../shared_dependency/base_dependencies


dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  test: ^1.25.15
  mocktail: ^1.0.4
  injectable_generator: ^2.7.0
  very_good_analysis: 6.0.0