name: login
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  ui_dependencies:
    path: ../../../core/shared_dependency/ui_dependencies

  domain:
    path: ../../../domain

  utils:
    path: ../../../core/utils

dev_dependencies:
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: 6.0.0
  build_runner: ^2.1.0
  injectable_generator: ^2.7.0
