name: network
description: A package that handles network requests.

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.3.3
  get_it: ^7.6.4
  injectable: ^2.5.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

