name: network
description: A package that handles network requests.

environment:
  sdk: ^3.5.0

dependencies:
  base_dependencies:
    path: ../shared_dependency/base_dependencies

  dio: ^5.3.3

  utils:
    path: ../utils

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  test: ^1.25.15
  mocktail: ^1.0.4
  very_good_analysis: 6.0.0