name: domain
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0


dependencies:
  utils:
    path: ../core/utils

  base_dependencies:
    path: ../core/shared_dependency/base_dependencies
dev_dependencies:
  bloc_test: 9.1.7
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  test: ^1.25.15
  mocktail: ^1.0.4
  very_good_analysis: 6.0.0

